apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gateway-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gateway-service
    spec:
      containers:
        - name: gateway-service
          image: {{ .Values.gatewayService.image.repository }}:{{ .Values.gatewayService.image.tag }}
          command:
            - sh
            - '-c'
            - 'uvicorn main:app --reload --host 0.0.0.0'
          envFrom:
            - configMapRef:
                name: gateway-configmap
          ports:
            - containerPort: {{ .Values.gatewayService.targetPort }}
          volumeMounts:
            - name: gtw-volume
              mountPath: /app
      volumes:
        - name: gtw-volume
          persistentVolumeClaim:
            claimName: gtw-service-volume

