apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-gateway-service
  ports:
    - protocol: TCP
      port: {{ .Values.gatewayService.port }}
      targetPort: {{ .Values.gatewayService.port }}