apiVersion: v1
kind: PersistentVolume
metadata:
  name: odr-volume-pv-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./orders"
  claimRef:
    name: odr-service-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odr-service-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi